# Site Settings
title:               Blogging as Brian
description:         Insert any very witty phrase right here...
show_downloads:      false
is_project_page:     true
google_analytics:

plugins:
 - jekyll-seo-tag

# Build Settings
theme: jekyll-theme-cayman
