# Site Settings
title:              "Distributed Thoughts"
tagline:            "A blog wherein Brian Dean attempts to diminish confusion and encourage understanding"
description:        "Thoughts, technical posts, and how-to articles about anything in IT that I'm learning or want to help you learn."
site_name:          "bthedean.github.io"
project_url:        "https://github.com/BtheDean/bthedean.github.io"
baseurl:            ""
blog_url:           "https://bthedean.github.io"
google_analytics:

# About/contact
author:
  name:       Brian Dean
  github:     BtheDean
  url:        https://github.com/BtheDean
  email:      bthedean@protonmail.com
  twitter:    BtheDean

# Gems
plugins:
  - jekyll-seo-tag

#Others
markdown: kramdown