# Site Settings
title:               Blogging as Brian
description:         Insert any very witty phrase right here...
show_downloads:      false
google_analytics:

# About / Contact
 -author:
 -  name:              Brian Dean
 -  url:               https://twitter.com/BtheDean
 -  email:             bthedean@protonmail.com
 -  github:            BtheDean
 -  twitter:           BtheDean

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build Settings
theme: jekyll-theme-cayman

exclude:
  - Gemfile
  - README.md
