# Site Settings
title:               Blogging as Brian
description:         Insert any very witty phrase right here...
show_downloads:      false
is_project_page:     true
google_analytics:

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Build Settings
theme: jekyll-theme-cayman
