# Site Settings
title:               Blogging as Brian
description:         Insert any very witty phrase right here...
show_downloads:      false
google_analytics:

markdown: kramdown

plugins:
  - jekyll-seo-tag

# Build Settings
theme: jekyll-theme-cayman
