# Site Settings
title:               "Blogging as Brian"
description:         "Insert a very witty phrase right here..."
baseurl:	     ""
show_downloads:      true
google_analytics:

plugins:
 - jekyll-seo-tag

# Build Settings
theme: jekyll-theme-cayman
